# Generated by Django 4.0.5 on 2022-06-26 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0005_rename_comments_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='article',
            name='comments',
            field=models.IntegerField(default=0),
        ),
    ]
