# Generated by Django 4.0.5 on 2022-06-28 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_alter_comment_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
