# Generated by Django 4.0.5 on 2022-07-03 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomePage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('main_title', models.CharField(max_length=255)),
                ('main_img_source', models.CharField(blank=True, max_length=255)),
                ('main_img_legend', models.CharField(blank=True, max_length=255)),
                ('carousel_name', models.CharField(blank=True, max_length=255)),
                ('first_title_h3', models.CharField(blank=True, max_length=255)),
                ('first_p', models.TextField(blank=True)),
                ('second_img_source', models.CharField(blank=True, max_length=255)),
                ('second_img_alt', models.CharField(blank=True, max_length=255)),
                ('preview_text', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Presentation',
        ),
    ]
