# Generated by Django 4.0.5 on 2022-07-04 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_newblock'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newblock',
            old_name='image',
            new_name='image1',
        ),
        migrations.RenameField(
            model_name='newblock',
            old_name='paragraph',
            new_name='link_text1',
        ),
        migrations.RenameField(
            model_name='newblock',
            old_name='title',
            new_name='title1',
        ),
        migrations.AddField(
            model_name='newblock',
            name='image2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='image3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='link_text2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newblock',
            name='link_text3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newblock',
            name='paragraph1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newblock',
            name='paragraph2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newblock',
            name='paragraph3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='newblock',
            name='title2',
            field=models.CharField(default='my title here', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='newblock',
            name='title3',
            field=models.CharField(default='my title here', max_length=255),
            preserve_default=False,
        ),
    ]
