# Generated by Django 4.0.5 on 2022-07-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0004_rename_image_newblock_image1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newblock',
            name='title1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='newblock',
            name='title2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='newblock',
            name='title3',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
