# Generated by Django 4.0.5 on 2022-07-05 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_alter_newblock_title1_alter_newblock_title2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='highligted_text',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='highligted_text1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='highligted_text2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='highligted_text3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='text_effect1',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='text_effect12',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='text_effect13',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='text_effect2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='text_effect21',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='text_effect23',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='text_effect3',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='text_effect32',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='newblock',
            name='text_effect33',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
