# Generated by Django 4.0.5 on 2022-07-05 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_homepage_highligted_text_newblock_highligted_text1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='highligted_text',
            new_name='highlighted_text',
        ),
        migrations.RenameField(
            model_name='newblock',
            old_name='highligted_text1',
            new_name='highlighted_text1',
        ),
        migrations.RenameField(
            model_name='newblock',
            old_name='highligted_text2',
            new_name='highlighted_text2',
        ),
        migrations.RenameField(
            model_name='newblock',
            old_name='highligted_text3',
            new_name='highlighted_text3',
        ),
    ]
