# Generated by Django 4.0.5 on 2022-08-24 10:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0009_alter_homepage_first_link_alter_homepage_second_link'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='newblock',
            options={'ordering': ['-date']},
        ),
        migrations.AddField(
            model_name='newblock',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date de publication'),
            preserve_default=False,
        ),
    ]
