# Generated by Django 4.0.5 on 2022-09-27 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0011_remove_newblock_highlighted_text1_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newblock',
            name='image2',
        ),
        migrations.RemoveField(
            model_name='newblock',
            name='image3',
        ),
        migrations.RemoveField(
            model_name='newblock',
            name='link2',
        ),
        migrations.RemoveField(
            model_name='newblock',
            name='link3',
        ),
        migrations.RemoveField(
            model_name='newblock',
            name='link_text2',
        ),
        migrations.RemoveField(
            model_name='newblock',
            name='link_text3',
        ),
        migrations.RemoveField(
            model_name='newblock',
            name='paragraph2',
        ),
        migrations.RemoveField(
            model_name='newblock',
            name='paragraph3',
        ),
        migrations.RemoveField(
            model_name='newblock',
            name='title2',
        ),
        migrations.RemoveField(
            model_name='newblock',
            name='title3',
        ),
        migrations.AlterField(
            model_name='newblock',
            name='image1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='newblock',
            name='link1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='newblock',
            name='link_text1',
            field=models.TextField(blank=True, null=True),
        ),
    ]
