# Generated by Django 4.0.5 on 2022-09-27 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0012_remove_newblock_image2_remove_newblock_image3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='newblock',
            name='video_tile',
            field=models.CharField(default='Mon application kivy CryptoGUI', max_length=128),
            preserve_default=False,
        ),
    ]
