# Generated by Django 4.0.5 on 2022-09-27 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0014_newblock_title_btn_displa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newblock',
            old_name='title_btn_displa',
            new_name='title_btn_display',
        ),
    ]
