# Generated by Django 4.0.5 on 2022-09-27 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0015_rename_title_btn_displa_newblock_title_btn_display'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newblock',
            old_name='video_tile',
            new_name='video_title',
        ),
    ]
