# Generated by Django 4.0.5 on 2022-08-20 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChessGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent1', models.CharField(blank=True, default='Ekla', max_length=255)),
                ('opponent2', models.CharField(blank=True, max_length=255)),
                ('opening', models.CharField(blank=True, max_length=255)),
                ('date', models.DateField(verbose_name='partie disputée le:')),
                ('PNG', models.FileField(blank=True, null=True, upload_to='chess/chessgames')),
                ('iframe_link', models.URLField(blank=True)),
                ('slug', models.SlugField(max_length=128)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
    ]
