# Generated by Django 4.0.5 on 2022-09-04 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptonet',
            name='key',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
