# Generated by Django 4.0.5 on 2022-09-19 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0003_remove_cryptonet_name_cryptonet_slug_cryptonet_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cryptonet',
            name='key',
            field=models.CharField(default=b'', max_length=255),
        ),
    ]
