# Generated by Django 4.0.5 on 2022-09-20 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0004_alter_cryptonet_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptonet',
            name='keyFile',
            field=models.FileField(blank=True, null=True, upload_to='keyfiles'),
        ),
    ]
