# Generated by Django 4.0.5 on 2022-09-22 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crypto', '0005_cryptonet_keyfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cryptonet',
            old_name='keyFile',
            new_name='keyfile',
        ),
    ]
